name = "ConjugateGradient"
uuid = "544ed34a-48a4-42df-8f69-6656fd9f4d48"
authors = ["Éric Thiébaut <https://github.com/emmt>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NumOptBase = "19474dce-faed-4c37-be94-3eba84df10eb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
NumOptBase = "0.1.1"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
